import type { Metadata } from "next";
import Script from "next/script";

// import { Geist, Geist_Mono } from "next/font/google";
import { Exo } from "next/font/google";
import Common from "@/utils/common";

const exo = Exo({ subsets: ["latin"] });

import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Payyng App - Revolutionalizing Bill Payment In Nigeria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Common>
        <body className={`${exo.className}  antialiased`}>{children}</body>
      </Common>

      <Script id="clarity-script" strategy="afterInteractive">
        {` (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "qfbu76rrtt");
          `}
      </Script>
    </html>
  );
}
// ${geistMono.variable}
